# Generated by Django 5.2.3 on 2025-07-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buyeraddress",
            name="address_line2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
