name: Django Tests on Push

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      RAZORPAY_CLIENT_ID: ${{ secrets.RAZORPAY_CLIENT_ID }}
      RAZORPAY_CLIENT_SECRET: ${{ secrets.RAZORPAY_CLIENT_SECRET }}
      RAZORPAY_BASE_URL: ${{ secrets.RAZORPAY_BASE_URL }}
      DJANGO_SETTINGS_MODULE: core.settings
      DB_NAME: test_db
      DB_USER: test_user
      DB_PASSWORD: test_password
      DB_HOST: localhost
      DB_PORT: 5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ./core

    - name: Run Django Migrations
      run: python manage.py migrate --noinput
      working-directory: ./core

    - name: Run Django Tests
      run: python manage.py test
      working-directory: ./core
